[package]
name = "dfs_storage"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "*"
multihash = "0.14"
serde = { version = "1.0", features = ["derive"] }